language: objective-c
rvm:
  - 2.2
osx_image: xcode8
before_install:
  - (ruby --version)
  - sudo chown -R travis ~/Library/RubyMotion
  - sudo mkdir -p ~/Library/RubyMotion/build
  - sudo chown -R travis ~/Library/RubyMotion/build
  - sudo motion update 
script:
  - rake spec:osx:all
  - rake spec:simulator:ios:all
  - rake spec:simulator:tvOS
