language: objective-c
rvm:
  - system
osx_image: xcode7.3
before_install:
  - (ruby --version)
  - sudo chown -R travis ~/Library/RubyMotion
  - sudo mkdir -p ~/Library/RubyMotion/build
  - sudo chown -R travis ~/Library/RubyMotion/build
  - brew install axel
  - sudo motion update 
script:
  - rake spec:osx:all
  - rake spec:simulator:ios:all
  - rake spec:simulator:tvOS
